user register add
izumitomo/twitter-clone pull request #1
Opened 2022-03-09 14:14 UTC by izumitomo

2022-03-10 08:54 UTC, kunikida007 reviewed
テストを書いてみましょう！
最初は難しいかもしれないのでサイトを参考にしたり、
slackで質問しながら試行してみてください。

2022-03-10 08:54 UTC, kunikida007 commented on .gitignore
> +.DS_Store
末尾に改行を入れましょう。
https://qiita.com/norikt/items/83674fadd79a88bf7824

2022-03-10 08:54 UTC, kunikida007 commented on account/templates/account/start.html
> +
空行いらないです。

2022-03-10 08:54 UTC, kunikida007 commented on account/tests.py
> +from django.test import TestCase
テストを書いてみましょう！

2022-03-10 08:54 UTC, kunikida007 commented on account/models.py
> +from statistics import mode
使っていない場合は消しましょう。

2022-03-11 05:59 UTC, izumitomo commented on .gitignore
> +.DS_Store
修正しました。

2022-03-11 05:59 UTC, izumitomo commented on account/templates/account/start.html
> +
修正しました。

2022-03-11 05:59 UTC, izumitomo commented on account/models.py
> +from statistics import mode
修正しました。

2022-03-11 06:19 UTC, izumitomo commented on account/tests.py
> +from django.test import TestCase
分かりました！
あと、同一名ユーザの登録を受け付けない方法が分からずに実装を諦めたのですが、何か参考になるサイトやコードはないでしょうか？

2022-03-11 06:25 UTC, izumitomo commented on account/tests.py
> +from django.test import TestCase
了解です！

2022-03-11 06:25 UTC, izumitomo commented
テストを追加しました。
レビューよろしくお願いします。
それと、同一ユーザ名の登録を受け付けない方法が分からずに実装を諦めたのですが、何か参考になるサイトやコードはないでしょうか？

2022-03-12 00:10 UTC, kunikida007 commented on account/tests.py
> +    def test_statis(self):
statisという命名はどういう意図でつけられたのでしょうか？

2022-03-12 00:10 UTC, kunikida007 commented on account/tests.py
> +        self.assertTemplateUsed(self.response, 'account/register.html')
テスト実施結果のスクショ等もらえると助かります！

2022-03-12 02:51 UTC, izumitomo commented on account/tests.py
> +    def test_statis(self):
statusのミスですね。

2022-03-12 02:52 UTC, izumitomo commented on account/tests.py
> +
了解です。

2022-03-12 03:04 UTC, izumitomo commented on account/models.py
> +    password = models.CharField(max_length=30)
了解です。

2022-03-12 03:10 UTC, izumitomo commented
<img width="333" alt="image" src="https://user-images.githubusercontent.com/90303089/158001435-3115bb1d-9ab0-43c8-890c-7b346a180fdf.png">

テスト結果です。

2022-03-12 05:39 UTC, kunikida007 commented on account/admin.py
> +admin.site.register(Account)
このファイルをはじめ、末尾に改行がないことを示す⊝マークがついているものには末尾に改行を挿入してください。pythonは普通に動きますが、Cなどでは最後の改行がないことで「文字＋改行」で構成される「行」が認識されないことがあるようです。
[https://bottoms-programming.com/archives/indent-tab-space-and-new-line.html](https://github.com/kunikida007/tw/pull/url)
手持ちのエディタに「末尾に空白行を入れる」設定があればオンにしておくとよいと思います。

2022-03-12 05:40 UTC, kunikida007 commented
> テストを追加しました。 レビューよろしくお願いします。 それと、同一ユーザ名の登録を受け付けない方法が分からずに実装を諦めたのですが、何か参考になるサイトやコードはないでしょうか？

見逃してました。申し訳ないです。。
AbstractUserやAbstractBaseUserを継承したカスタムユーザーモデルを使うことで実装できると思います。

2022-03-12 09:04 UTC, izumitomo commented on account/admin.py
> +admin.site.register(Account)
了解です！

2022-03-12 13:22 UTC, izumitomo commented
AbstractUserモデルを継承したものを作成しているんですが、
python manage.py migrate
を実行した際にこのような、ユニーク制約のあるカラムに既に重複した値を入れようとしているというエラーが出てしまうのですが、解決方法が分かりません……。

<img width="449" alt="image" src="https://user-images.githubusercontent.com/90303089/158019498-0806c659-dae9-41cc-8c9b-d578fea9fd3b.png">

2022-03-12 14:59 UTC, kunikida007 commented
> AbstractUserモデルを継承したものを作成しているんですが、 python manage.py migrate を実行した際にこのような、ユニーク制約のあるカラムに既に重複した値を入れようとしているというエラーが出てしまうのですが、解決方法が分かりません……。
> 
> <img alt="image" width="449" src="https://user-images.githubusercontent.com/90303089/158019498-0806c659-dae9-41cc-8c9b-d578fea9fd3b.png">

DBの中にすでに重複したレコードを登録してしまっていないか確認してみてください。

2022-03-13 07:59 UTC, izumitomo commented on account/models.py
> +    #name = models.CharField(max_length=30)
必要ないですが、変化を確認しやすいように便宜上残しているという状況です。
AbstractUserへの移行が上手くいけば、消去するつもりです。

2022-03-13 08:09 UTC, izumitomo commented on account/migrations/0001_initial.py
> +# Generated by Django 3.2.12 on 2022-03-09 09:03
すみません……。
どれが最新でどれを.gitignoreに含めるべきなのかが判断できません。

2022-03-13 13:15 UTC, izumitomo commented
migrationのエラーはDBを一旦全削除することで、上手くいきました。
色々なサイトを参考にして、forms.pyにpassword1,password2を追加したのですが、password1と、password2に同一のパスワードが入力されると、変数passwordにその値が格納される内部処理が働いているという認識なのですが、間違いないでしょうか？
ちなみに、現在はテストを書き直している途中です、

2022-03-14 05:11 UTC, kunikida007 commented on account/migrations/0001_initial.py
> +# Generated by Django 3.2.12 on 2022-03-09 09:03
最新の0002があることでそれ以外は動作に必要なくなります。makemigrationをすると新たにfileが作成されるので最新のもの以外は.gitignoreに含めるか消去しましょう。

2022-03-14 05:11 UTC, kunikida007 commented
> migrationのエラーはDBを一旦全削除することで、上手くいきました。 色々なサイトを参考にして、forms.pyにpassword1,password2を追加したのですが、password1と、password2に同一のパスワードが入力されると、変数passwordにその値が格納される内部処理が働いているという認識なのですが、間違いないでしょうか？ ちなみに、現在はテストを書き直している途中です、

間違いないと思います。

2022-03-14 05:12 UTC, kunikida007 commented on account/models.py
> +    #name = models.CharField(max_length=30)
了解です。

2022-03-14 07:49 UTC, izumitomo commented
テスト追加しました。
レビューよろしくお願いします！

2022-03-16 05:15 UTC, Akinori13 requested changes
いい感じです！コメントしました。
- 次の機能からはブランチ名に機能名（register）も入れてあげてください。

2022-03-16 05:15 UTC, Akinori13 commented on account/migrations/0002_auto_20220313_1736.py
> +# Generated by Django 3.2.12 on 2022-03-13 08:36
0001_initialが消えているので、再構築をお願いします！

2022-03-28 07:01 UTC, izumitomo commented on account/views.py
> +#from .forms import SignUpForm
了解です！

2022-03-28 07:06 UTC, izumitomo commented on account/views.py
> +        data = RegisterForm(request.POST)
そのように変更します。

2022-03-28 07:09 UTC, izumitomo commented on account/tests.py
> +
了解です！

2022-03-28 07:11 UTC, izumitomo commented on account/migrations/0002_auto_20220313_1736.py
> +# Generated by Django 3.2.12 on 2022-03-13 08:36
1次レビューで最新の0002以外を削除するように言われて削除してしまったのですが、再構築とは具体的に何をすればいいのでしょうか？

2022-03-28 07:12 UTC, izumitomo commented on account/tests.py
> +        # なぜ'account/registerというパスで指定できてるのかは分からない
いえ、自分のメモなので消去しておきますね。

2022-03-28 07:15 UTC, izumitomo commented on account/views.py
> +            return redirect('start')
手間ではありますが、ユーザ登録後にmypageにリダイレクトするのではなく通常のサインインする手順を体験してもらうために、初期画面に遷移させています。

2022-03-28 07:17 UTC, izumitomo commented on account/templates/account/register.html
> +                <!--<tr><td colspan='2'><input type="register" value="Register"></td></tr>　はボタンにならない-->
了解です。

2022-03-28 07:27 UTC, izumitomo commented on mysite/settings.py
> +STATIC_ROOT = os.path.join(BASE_DIR, 'static')
変更しました！

2022-03-28 07:45 UTC, izumitomo commented on account/tests.py
> +class RegisterErrorTests(TestCase):
追加しました！

2022-03-28 07:52 UTC, izumitomo commented
テストを追加しました！
コメントにも書きましたが、1次レビューで0001_initialを削除してしまったのですが、自分の理解が間違っていたということでしょうか？

2022-03-30 13:12 UTC, Akinori13 requested changes
少しコメントしました

2022-03-30 13:12 UTC, Akinori13 commented on account/migrations/0002_auto_20220313_1736.py
> +# Generated by Django 3.2.12 on 2022-03-13 08:36
@izumitomo @kunikida007 
マイグレーションはチェーンですので、一つ前のマイグレーションファイルを削除した段階でチェーンが断ち切れてしまいます。

切断されたチェーンは戻せないので、再度作り直します。migrationsフォルダの0002を削除し、__init__.pyを追加（なぜ必要なのかは調べてください）します。そして、`python manage.py makemigrations`を実行します。

この部分はとても難しく、自分も案件に入るまで深く考えていませんでした。
二人でDB定義をしていた時に、チェーンが分かれてしまいました。端的に説明すると、0004に続くマイグレーションファイルを二人がそれぞれ作成（0005aと0005b）してしまったわけです。0004から0005aには続きますが、0005aと0005bはつながりませんから、0005bがDBに反映されず、問題が発生してしまったわけです。

2022-03-30 13:12 UTC, Akinori13 commented on account/views.py
> +            account.save()
`commit=False`の理由はありますか

2022-03-31 05:53 UTC, izumitomo commented on account/views.py
> +            account.save()
特にありません。
参考にしたコードをそのまま持って来たものなので、削除しておきますね。

2022-03-31 06:24 UTC, izumitomo commented on account/migrations/0002_auto_20220313_1736.py
> +# Generated by Django 3.2.12 on 2022-03-13 08:36
何となくですが、理解しました。
ということは0001を削除するべきではなく、.gitignoreファイルに含めるべきだったのでしょうか。

2022-03-31 06:29 UTC, izumitomo commented
コメントを基に修正しました！

2022-04-01 10:26 UTC, Akinori13 requested changes
いくつかコメントしました！

2022-04-01 10:26 UTC, Akinori13 commented on account/views.py
> +from .models import Account
使わないなら消しちゃってください

2022-04-01 10:26 UTC, Akinori13 commented on account/views.py
> +from .forms import RegisterForm
そのままでも構いませんが、1行目と2行目に空行を挟むことで、Djangoのプログラムを利用しているのかが分かりやすくなります

2022-04-01 10:26 UTC, Akinori13 commented on account/views.py
> +            account.save()
必要ない処理が含まれています

2022-04-01 10:26 UTC, Akinori13 commented on account/tests.py
> +from django.test import TestCase, Client
必要ないimportは削除してください

2022-04-01 12:28 UTC, izumitomo commented on account/views.py
> +from .models import Account
了解です！

2022-04-01 12:28 UTC, izumitomo commented on account/views.py
> +from .forms import RegisterForm
了解です！

2022-04-01 12:45 UTC, izumitomo commented on account/views.py
> +            account.save()
修正しました。

2022-04-01 12:45 UTC, izumitomo commented on account/tests.py
> +from django.test import TestCase, Client
了解です。

2022-04-01 12:51 UTC, izumitomo commented
修正しました！

2022-04-02 08:42 UTC, Akinori13 commented on account/tests.py
> +        self.assertTemplateUsed(self.response, 'account/register.html')
下と重複

2022-04-02 08:42 UTC, Akinori13 requested changes
一点だけコメントしました

2022-04-02 08:49 UTC, izumitomo commented on account/tests.py
> +        self.assertTemplateUsed(self.response, 'account/register.html')
すみません！
修正しました！

2022-04-02 08:49 UTC, izumitomo commented
修正しました！

2022-04-02 08:54 UTC, Akinori13 commented on account/tests.py
> +    def test_blank_username(self):
一番下のメソッド名と重複

2022-04-02 08:56 UTC, izumitomo commented
同じミスをすみません……
修正しました。

2022-04-02 08:58 UTC, Akinori13 commented
LGTM!

2022-04-02 09:05 UTC, Akinori13 approved these changes

2022-04-02 09:05 UTC, merged